services:
  ddns:
    build: .
    image: cloudflare-ip-updater:latest
    container_name: cloudflare-ip-updater
    restart: unless-stopped
    environment:
      - CLOUDFLARE_ZONE_ID=
      - CLOUDFLARE_API_TOKEN=
      - DOMAIN=
      - UNPROXIED_RECORDS=
      - DISCORD_WEBHOOK_URL=
